language: node_js
node_js:
  - "lts"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test

jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: trusty
    - os: windows
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode11.2
    - os: osx
      osx_image: xcode11.1
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4