version: '3.1'

services:
  app:
    image: sorta/headcanon-generator
    #ports:
    #  - "5000:5000"

    env_file:
      - .env.production
      - .env.production.local

    environment:
      - NODE_ENV=production

    deploy:
      replicas: 2
  
  proxy:
    image: sorta/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ~/.caddy:/root/.caddy
